name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Package
        run: |
          zip -r package.zip \
            theme.json \
            theme.css \
            README.md \
            README_zh_CN.md \
            LICENSE \
            icon.png \
            preview.png

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "package.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
